### ISSUE TITLE
You must enter a collection slug/ID.

### ISSUE THREAD

**Issue by YEsmaR1** [xSetrox/iRightClick#8] opened 2022-01-19 23:08 UTC
when i do 'main.py boredapeyachtclub'  it says " You must enter a collection slug/ID."

**Comment by shishtaouk09** [comment] 2022-01-23 21:55
did u found a fix ?

**Comment by xSetrox** [comment] 2022-02-03 02:03
Can you try running it with `python3 main.py boredapeyachtclub`? Or `python2` as a replacement, or `py`, whatever you run python with.

**Comment by xSetrox** [comment] 2022-02-03 02:08
Closing as duplicate of #6

**Closed by xSetrox** 2022-02-03 02:08 UTC
